spring.application.name=banco-xyz-batch

spring.datasource.url=jdbc:postgresql://localhost:5432/banco_xyz
spring.datasource.username=banco
spring.datasource.password=banco
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false

legacy.data.week=semana_2
batch.chunk-size=5
batch.thread-pool-size=3
batch.skip-limit=10
batch.retry-limit=2
batch.review-skip-threshold=3

logging.level.org.springframework.jdbc.core=INFO
