spring.application.name=bff-atm
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=cl.duoc.backendiii.events
spring.kafka.consumer.properties.spring.json.use.type.headers=true
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
server.port=8083
core.banking.url=${CORE_BANKING_URL:http://localhost:8080}
channel.name=ATM
channel.path-pattern=/atm/**
channel.role=ATM
atm.max-withdrawal-amount=200000
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

server.ssl.enabled=${BFF_SSL_ENABLED:true}
server.ssl.key-store=${SSL_KEYSTORE:classpath:keystore.p12}
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD:changeit}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=bff-local

security.users.web.password=${WEB_PASSWORD:web123}
security.users.mobile.password=${MOBILE_PASSWORD:mobile123}
security.users.atm.password=${ATM_PASSWORD:atm123}
